name: acecook
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.3
  shared_preferences:
  file: ^6.1.4
  flutter_bloc: ^8.0.1
  go_router: ^5.2.1
  equatable: ^2.0.5
  font_awesome_flutter: ^10.4.0
  json_serializable: ^6.6.2
  json_annotation: ^4.8.1
  chopper: ^6.1.3
  carousel_slider: ^4.2.1
  dropdown_button2: ^1.9.2
  qr_code_scanner: ^1.0.1
  rxdart: ^0.27.7
  logging: ^1.2.0
  flutter_secure_storage: ^8.0.0
  barcode_widget: ^2.0.4
  fluttertoast: ^8.2.2

  google_mlkit_text_recognition: ^0.10.0
  permission_handler: ^10.2.0
  image_picker: ^1.0.2
  dotted_border: ^2.0.0+3
  flutter_camera_overlay: ^0.1.1
  image_cropper: ^5.0.0
  screenshot: ^2.1.0
  path_provider: ^2.1.0
  image_gallery_saver: '^2.0.3'
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  chopper_generator: ^6.0.1

flutter:
  uses-material-design: true



  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
